# Task M3 T01

In [183]:
import numpy as np
from numpy import random as rd
from scipy import stats as st
import math

## Exercise 1

Create a function that given a one dimension array, it returns a basic statistic summary of the data. If the function detects that the array has more than one dimension, it has to show an error message.

In [184]:
# Function basic_summary()
def basic_summary(arr):
    if arr.ndim != 1:
        print("ERROR: The array must be uni-dimensional!!!")
    else:
        # Mean
        arr_mean = np.mean(arr)
        print("Mean: {}".format(arr_mean))
        # Median
        arr_median = np.median(arr)
        print("Median: {}".format(arr_median))
        # Standard deviation
        arr_std = np.std(arr)
        print("Standard deviation: {:.2f}".format(arr_std))
        # Variance
        arr_var = np.var(arr)
        print("Variance: {:.2f}".format(arr_var))
        # Mode
        arr_mode = st.mode(arr)
        print("Mode \telement: {}\n\tcount: {}".format(arr_mode[0][0],arr_mode[1][0]))

In [185]:
# TEST
arr_1 = rd.randint(10, size = 100) # 1D random array must show a basic statistic summary.
arr_2 = rd.randint(10, size = (5,100)) #2D random matrix must show an error message.

print("TEST 1:\n\nExpected result: Show basic statistic summary\n\nResult:\n")
basic_summary(arr_1)
print("\nTEST 2:\n\nExpected result: Error message\n\nResult:\n")
basic_summary(arr_2)

TEST 1:

Expected result: Show basic statistic summary

Result:

Mean: 3.93
Median: 3.5
Standard deviation: 2.77
Variance: 7.69
Mode 	element: 1
	count: 14

TEST 2:

Expected result: Error message

Result:

ERROR: The array must be uni-dimensional!!!


## Exercise 2

Create a function that generates a square NxN of random numbers in range 0 to 100.

In [188]:
# MAIN FUNCTION:
# Function create_square()
#    Parameters:
#    - rows_num: gets the number of rows that the square must have.
#    - columns_num: gets the numbre of columns that the square must have.

def create_square(size):
    result = rd.randint(100, size = (size, size))
    return result

# OTHERS FUNCTIONS:
# Function get_size()
def get_size():
    size = int(input("Enter the size of the square: "))
    if size < 1:
        print("ERROR: Size number must be at least 1!")
        size = get_size()
    return size

In [189]:
# TEST
# Getting the parameters
size = get_size()

# Generating the square
square_1 = create_square(size)
print("\nTEST:\nSquare {} x {}: \n\n{}".format(size, size, square_1))

Enter the size of the square: 3

TEST:
Square 3 x 3: 

[[57 39 89]
 [98 23 18]
 [21 33 77]]


## Exercise 3

Create a function that given a two dimension table NxM calculates the totals in each row and in each column.

In [192]:
# MAIN FUNCTION
# Function get_totals()
def get_totals(table):
    sum_rows(table)
    sum_columns(table)

# OTHER FUNCTIONS
# Function get_rows()
def get_rows():
    rows = int(input("Enter the number of rows: "))
    if rows < 1:
        print("ERROR: Rows number must be at least 1!")
        rows = get_rows()
    return rows

# Function get_columns()
def get_columns():
    columns = int(input("Enter number of columns: "))
    if columns < 1:
        print("ERROR: Columns number must be at least 1!")
        columns = get_columns()
    return columns

# Function get_table()
def get_table():
    rows = get_rows()
    columns = get_columns()
    table = rd.randint(10, size = (rows, columns))
    return table

# Function sum_rows()
def sum_rows(table):
    print("\nRow totals:")
    i = 0
    for element in table:
        i += 1
        print("\tTotal in row {} is {}".format(i, element.sum()))

def sum_columns(table):
    changed_axis_tb = np.stack(table, axis =1)
    print("\nColumn totals:")
    i = 0
    for element in changed_axis_tb:
        i += 1
        print("\tTotal in column {} is {}".format(i, element.sum()))
        

In [193]:
# TEST
table = get_table()
print(table)
get_totals(table)

Enter the number of rows: 5
Enter number of columns: 7
[[8 6 2 9 3 7 8]
 [1 7 3 0 9 2 0]
 [3 2 1 7 9 0 5]
 [5 3 9 5 5 5 4]
 [8 4 1 4 3 7 1]]

Row totals:
	Total in row 1 is 43
	Total in row 2 is 22
	Total in row 3 is 27
	Total in row 4 is 36
	Total in row 5 is 28

Column totals:
	Total in column 1 is 25
	Total in column 2 is 22
	Total in column 3 is 16
	Total in column 4 is 25
	Total in column 5 is 29
	Total in column 6 is 21
	Total in column 7 is 18


## Exercise 4

Create a function that calculates the correlation coeficient.

In [196]:
# MAIN FUNCTION - get_corrcoef()
def get_corrcoef(arr1, arr2):
    # Calculate means from arr1 and arr2
    mean1 = get_mean(arr1)
    mean2 = get_mean(arr2)
    
    # Calculate numerator (sum covar)
    numerator = 0
    for i in range(len(arr1)):
        numerator += (arr1[i]-mean1)*(arr2[i]-mean2)
        
    # Caculate denominator - it is necessary to import math to calculate the square root with math.sqrt
    denominator = math.sqrt(get_sum_squares(arr1, mean1) * get_sum_squares(arr2, mean2))
    
    # Calculate correlation coeficient
    result = numerator / denominator
    return result

# OTHER FUNCTIONS
# Function get_mean():
def get_mean(arr):
    sum = 0
    for element in arr:
        sum += element
    return sum/len(arr)   

# Function get_squares
def get_sum_squares(arr, mean):
    sum = 0
    for element in arr:
        sum += (element - mean) ** 2
    return sum

In [199]:
# TESTS
arr1 = rd.rand(10)
arr2 = rd.rand(10)

print("TEST:\nExpected result vs result:\n{} (expected result) \n{} (result)".format(np.corrcoef(arr1,arr2)[0,1], get_corrcoef(arr1, arr2)))

TEST:
Expected result vs result:
0.012210708667924635 (expected result) 
0.01221070866792465 (result)
